# Gets the slim version from a DockerHub
FROM python:alpine3.19

# set /app as the working directory
# copy content in local src folder to /app directory within the container.
WORKDIR /app
COPY ./src .

# base directory
# |
# -- src
# ----- | sourcecode
# -- Dockerfile
